### ISSUE TITLE
Missing the `fs-extra` module used by build.js

### ISSUE THREAD

**Issue by markov00** [accurat/accurapp#8]
$ yarn build
    yarn build v0.21.3
    $ accurapp-scripts build
    module.js:472
        throw err;
        ^

    Error: Cannot find module 'fs-extra'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/marco/Workspaces/Accurat/tools/prova/node_modules/accurapp-scripts/scripts/build.js:22:10)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
    error Command failed with exit code 1.

**Comment by caesarsol** [comment]
Build is actually still unsupported... The code inside is old 😄
