### ISSUE TITLE
Show help if app name is missing

### ISSUE THREAD

**Issue by markov00** [accurat/accurapp#9]
Instead of throwing an error, it's better to show the usage help if missing on the CLI

    $ create-accurapp
    path.js:7
        throw new TypeError('Path must be a string. Received ' + inspect(path));
        ^

    TypeError: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.resolve (path.js:1146:7)
        at Object.<anonymous> (/Users/marco/.config/yarn/global/node_modules/create-accurapp/index.js:91:21)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.runMain (module.js:605:10)
        at run (bootstrap_node.js:420:7)

**Comment by caesarsol** [comment]
@marcofugaro isn't it working?

**Comment by caesarsol** [comment]
https://github.com/accurat/accurapp/commit/16f194a9d8f8219004566a419c50ef8bb787e21f#diff-30308b1fc1518927359a6eb82d357ae4R97

**Comment by marcofugaro** [comment]
not in latest release, tried it.

let's test it better tomorrow @caesarsol
